Version 4.1.0
- Added invalid file detection and capability modification
- Added dynamic modification of the HTML and removed redundancies
- Fixed repeated baseURL calculation and saving
- Added Playwright tests
- Added testing and release jobs to deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,9 +1,12 @@
-name: Deploy
+name: Build - Test - Release - Deploy
 
 on:
   push:
-    branches:
-      - main
+    tags:
+      - 'v[0-9]+.[0-9]+.[0-9]+'
+
+permissions:
+  contents: write
 
 jobs:
   build:
@@ -15,10 +18,13 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Setup Node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
+        with:
+          node-version: lts/*
+          cache: 'npm'
 
       - name: Install dependencies
-        uses: bahmutov/npm-install@v1
+        run: npm ci
 
       - name: Build project
         run: npm run build
@@ -35,11 +41,96 @@ jobs:
           name: example-game
           path: ./assets/game
 
+  test:
+    name: Test
+    runs-on: ubuntu-latest
+    needs: build
+    timeout-minutes: 60
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-node@v4
+        with:
+          node-version: lts/*
+          cache: 'npm'
+
+      - name: Install dependencies
+        run: npm ci
+
+      - name: Install Playwright Browsers
+        run: npx playwright install --with-deps
+
+      - name: Run Playwright tests
+        run: npx playwright test
+
+      - uses: actions/upload-artifact@v4
+        if: ${{ !cancelled() }}
+        with:
+          name: playwright-report
+          path: playwright-report/
+          retention-days: 30
+
+  verify:
+    name: Verify main branch
+    runs-on: ubuntu-latest
+    needs: test
+
+    steps:
+      - name: Checkout code for deploy check
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Verify commit is on main branch
+        id: check_branch
+        run: |
+          # Check if the commit SHA associated with the tag exists on the remote 'origin/main' branch
+          if git branch -r --contains ${{ github.sha }} | grep -q 'origin/main$'; then
+            echo "Commit ${{ github.sha }} found on origin/main"
+            exit 0
+          else
+            echo "::error::Commit ${{ github.sha }} not found on origin/main branch. Skipping release."
+            exit 1
+          fi
+
+  release:
+    name: Create Release
+    runs-on: ubuntu-latest
+    needs: verify
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: production-files
+
+      - name: Zip artifact contents
+        run: |
+          echo "Zipping contents of directory 'production-files'..."
+          cd production-files
+          zip -r ../static.zip .
+          cd ..
+          echo "Created zip file: static.zip"
+
+      - name: Create Release and Upload Asset
+        uses: softprops/action-gh-release@v2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: ${{ github.ref_name }}
+          name: ${{ github.ref_name }}
+          body_path: CHANGELOG.md
+          files: static.zip
+          draft: false
+          prerelease: false
+
   deploy:
     name: Deploy
-    needs: build
     runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main'
+    needs: verify
 
     steps:
       - name: Download build artifact
